# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "bento/ubuntu-16.04"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 8080, host: 8081
  config.vm.network "forwarded_port", guest: 8888, host: 8888
  
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  # config.vm.network "private_network", type: "dhcp"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "../", "/synced_folder"

  # config.vm.provision "file", source: "./serve_playbooks.py", destination: "serve_playbooks.py"

  # The following is adapted from
  # http://stackoverflow.com/a/37335639
  config.vm.provider "virtualbox" do |vb|
    mem_ratio = 3/4
    cpu_exec_cap = 75
    host = RbConfig::CONFIG['host_os']
    # Give VM 3/4 system memory & access to all cpu cores on the host
    if host =~ /darwin/
      cpus = `sysctl -n hw.ncpu`.to_i
      # sysctl returns Bytes and we need to convert to MB
      mem = `sysctl -n hw.memsize`.to_i / 1024^2 * mem_ratio
    elsif host =~ /linux/
      cpus = `nproc`.to_i
      # meminfo shows KB and we need to convert to MB
      mem = `grep 'MemTotal' /proc/meminfo | sed -e 's/MemTotal://' -e 's/ kB//'`.to_i / 1024 * mem_ratio
    else # Windows folks
      cpus = `wmic cpu get NumberOfCores`.split("\n")[2].to_i
      mem = `wmic OS get TotalVisibleMemorySize`.split("\n")[2].to_i / 1024 * mem_ratio
    end

    if cpus == 2
      cpus = 1
    elsif cpus > 2
      cpus = cpus - 2
    end
    # puts(mem)
    # puts(mem/1024)
    # puts(mem/1024^2)
    # puts "Provisioning VM with #{cpus} CPU cores (at #{cpu_exec_cap}%) and #{mem/1024} MB RAM."

    vb.customize ["modifyvm", :id, "--memory", mem/1024]
    vb.customize ["modifyvm", :id, "--cpus", cpus]

    vb.customize ["modifyvm", :id, "--cpuexecutioncap", cpu_exec_cap]

    vb.name = "lsd2017vm"
    # You might want to include the following for a GUI
    # vb.gui = true
  end

  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get update

    # sudo echo "LC_ALL=\"en_US.UTF-8\"" >> /etc/environment
    # sudo locale-gen UTF-8

    sudo apt-get install -y git
    sudo apt-get install -y wget

    echo "Think about installing MonoDevelop..."

    echo "Installing Java..."
    sudo apt-get -y install software-properties-common
    sudo add-apt-repository ppa:webupd8team/java
    sudo apt-get -y update
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
    sudo apt-get -y install oracle-java8-installer
    sudo update-java-alternatives -s java-8-oracle

    echo "Installing Go..."
    wget https://storage.googleapis.com/golang/go1.8.3.linux-amd64.tar.gz
    sudo tar -C /usr/local -xzf go1.8.3.linux-amd64.tar.gz
    echo "export PATH=$PATH:/usr/local/go/bin" >> $HOME/.profile
    echo "export GOPATH=/go_projects" >> $HOME/.profile

    echo "Installing Anaconda..."
    sudo wget https://repo.continuum.io/archive/Anaconda3-4.4.0-Linux-x86_64.sh -O ~/Anaconda3-4.4.0-Linux-x86_64.sh

    bash ~/Anaconda3-4.4.0-Linux-x86_64.sh -b
    
    echo ". $HOME/.bashrc" >> $HOME/.bash_profile
    echo "export PATH=$HOME/anaconda3/bin:$PATH" >> $HOME/.bash_profile
    echo "alias notebook='jupyter notebook --no-browser --ip=0.0.0.0 --NotebookApp.token=\\"\\"'" >> $HOME/.bash_profile
  
    export PATH="$HOME/anaconda3/bin:$PATH"

    $(which pip) install suplemon
    $(which pip) install bash_kernel
    #sudo chmod o+w /usr/local/
    #sudo $(which python) -m bash_kernel.install

    # this package is necessary for matplotlib to work and not installed by 
    # default
    sudo apt-get install -y libgl1-mesa-glx

    echo "==================================================================="
    echo "=                             DONE                                ="
    echo "==================================================================="
    echo "To log onto the VM:"
    echo "$ vagrant ssh"
    echo "To switch to the directory with teaching material:"
    echo "$ cd /synced_folder/notebooks"
    echo "To start the Jupyter notebook server:"
    echo "$ notebook"
  SHELL
end