version: "3"
services:
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "9700:9700"
    volumes:
      - ./01-http-input.conf:/etc/logstash/conf.d/01-http-input.conf
      - ./30-output.conf:/etc/logstash/conf.d/30-output.conf
    environment:
      - ES_HEAP_SIZE=512m
